[tools]
rojo = "rojo-rbx/rojo@7.4.0-rc2"
wally = "UpliftGames/wally@0.3.2"
selene = "Kampfkarren/selene@0.26.1"
luau-lsp = "JohnnyMorganz/luau-lsp@1.26.0"
run-in-roblox = "rojo-rbx/run-in-roblox@0.3.0"
darklua = "seaofvoices/darklua@0.12.1"
