[home]
includeReadme = false

title = "red"

gitSourceBranch = "main"
changelog = true
classOrder = []

[docusaurus]
url = "http://api.dig1tt.com"
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"

[footer]
style = "dark"
copyright = "Copyright © 2025 dig1t. Built with Moonwave and Docusaurus"
