[package]
name = "dig1t/red"
version = "2.0.0-dev.1"
description = "Lightweight, easy-to-use, and efficient event-driven library for Roblox. More information: https://github.com/dig1t/red"
license = "Apache-2.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

include = ["src", "default.project.json"]
exclude = ["src/**/*.spec.luau"]

[dependencies]
Promise = "dig1t/promise@1.1.2"
Util = "dig1t/util@1.0.13"
